import type { Metadata } from "next";
import "../globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Providers from "../providers";
import { Josefin_Sans } from 'next/font/google'

const josefin = Josefin_Sans({
  subsets: ['vietnamese'],
  display: 'swap',
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${josefin.className} antialiased bg-background`}
      >
        <div className="h-full relative">
          <Providers>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
                {children}
            </ThemeProvider>
          </Providers>
        </div>
      </body>
    </html>
  );
}
