import FooterComponent from "@/components/footer-component";
import HeaderComponent from "@/components/header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function CMSLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="flex flex-col gap-y-7 max-w-3xl mx-auto">
        <HeaderComponent />
        {children}
        <FooterComponent />
      </div>
      <div className="absolute h-full top-0 left-0 right-0 bottom-0 z-[-1]">
        <div className="bg-pattern bg-repeat opacity-[0.03] w-full h-full bg-[length:161px]" />
      </div>
    </>
  );
}
